version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: yarn install      # installs dependencies
      - run: yarn build         # runs your test suite

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
