version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Install Yarn"
          command: "curl -o- -L https://yarnpkg.com/install.sh | bash"
      - run:
          name: "Yarn Build"
          command: "yarn build"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
